In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
type(arr)

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
type(arr_2d)

arr_3d = np.array([[
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
    ])
type(arr_3d)
print(f"shape of tensor is {arr_3d.shape}")
print(f"size of tensor is {arr_3d.size}")

shape of tensor is (2, 2, 2)
size of tensor is 8


In [10]:
print(np.random.rand(4,4))

print(np.zeros((2,3),dtype=int))
print(np.zeros((5,5)))

print(np.ones((3,5)))

print(np.full((3,3),5)) #np.full(shape_of_tensor, value)

print(np.empty((3,3)))


[[0.70841622 0.1133329  0.62540218 0.15742572]
 [0.53744445 0.29222005 0.20825769 0.51309065]
 [0.23149251 0.7478354  0.47704266 0.57355627]
 [0.30117109 0.37780406 0.95435758 0.93681981]]
[[0 0 0]
 [0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


In [11]:
arr =np.arange(1,11,1)
print(arr.reshape(5, 2))
print(arr.flatten()) 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(np.linspace(1,10,11))

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [13]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
print(np.intersect1d(arr1, arr2))

print(arr1 + arr)


[]
[ 1.13469214  2.30730176  3.87938809  4.79874523  5.34345312  6.8378779
  7.37641985  8.37356933  9.96030183 10.07786511]


In [14]:
arr = np.random.rand(10,10,10)
np.save("dataset", arr)

In [15]:
np.load("./dataset.npy")

array([[[0.84361947, 0.38496011, 0.9966984 , 0.50916606, 0.36296136,
         0.99427337, 0.61113973, 0.71557146, 0.85353605, 0.54166145],
        [0.25105455, 0.73305335, 0.13473463, 0.98638262, 0.18915203,
         0.75560603, 0.3719081 , 0.30712963, 0.02055654, 0.51040476],
        [0.42063729, 0.8683313 , 0.6757667 , 0.07422116, 0.28612166,
         0.85715909, 0.50347236, 0.07124596, 0.69457577, 0.54794315],
        [0.56916165, 0.78599859, 0.50188028, 0.78143359, 0.57189453,
         0.14050313, 0.0389894 , 0.21627872, 0.9516912 , 0.24847682],
        [0.46579903, 0.46109243, 0.0312683 , 0.6665052 , 0.9163931 ,
         0.59340782, 0.16801646, 0.35706531, 0.77628953, 0.65512645],
        [0.58073673, 0.79384436, 0.76899617, 0.74073919, 0.41176154,
         0.49177931, 0.32454099, 0.74485023, 0.94608421, 0.88741839],
        [0.16565646, 0.46519517, 0.06534464, 0.84682125, 0.54391   ,
         0.85294366, 0.86608208, 0.57956705, 0.50055196, 0.37392616],
        [0.01570943, 0.0507

In [ ]:
print(np.mean(np.random.rand(23)))

In [16]:
print(np.mean(np.random.rand(23)))

0.5178834474619302


# now

In [33]:
arr = np.arange(1,31,1)
arr_2d = arr.reshape(10,3)
print(arr_2d)
print(arr_2d[0,:])
print(arr_2d[:,2])
print(arr_2d[1:4,1:2])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
[1 2 3]
[ 3  6  9 12 15 18 21 24 27 30]
[[ 5]
 [ 8]
 [11]]


In [44]:
x=arr[1:11]
x[:,np.newaxis]

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [42]:
print(arr_2d[[[1,2]],[1, 2]])

[[5 9]]


In [55]:
arr_2d = np.arange(1,26).reshape(5,5)
print(arr_2d)
print()
print(arr_2d[[1,2],[1,2]])
print()
print(arr_2d[ 1:3,1:3 ])
print()
print(arr_2d[[0,0,4,4],[0,4,0,4]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 7 13]

[[ 7  8]
 [12 13]]

[ 1  5 21 25]


In [64]:
arr_3d = np.arange(1,76).reshape(3,5,5)
arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]],

       [[51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75]]])

In [68]:
print(arr_3d[1,0,:])
print()
print(arr_3d[:, :, 4])
print()
print(arr_3d[:,1,:])

[26 27 28 29 30]

[[ 5 10 15 20 25]
 [30 35 40 45 50]
 [55 60 65 70 75]]

[[ 6  7  8  9 10]
 [31 32 33 34 35]
 [56 57 58 59 60]]


In [ ]:
arr[1:]